### ISSUE TITLE
关于词法分析小实验中报错范围的讨论

### ISSUE THREAD

**Issue by ZewanHuang** [BUAA-SE-Compiling/miniSysY-tutorial#11]
当输入含三个或更多个 `=` 时，比如 `a === b`，正确输出应该是什么？

-  `Eq\nAssign`
-  `Assign\nEq`
-  `Err` 并结束

**Comment by GeneraluseAI** [comment]
@Codevka

**Comment by GeneraluseAI** [comment]
应该输出

> 当输入含三个或更多个 `=` 时，比如 `a === b`，正确输出应该是什么？
> 
> * [ ]  `Eq\nAssign`
> * [ ]  `Assign\nEq`
> * [ ]  `Err` 并结束

我认为应该输出 Eq\nAssign

**Comment by ZewanHuang** [comment]
另外，我看到：
```c
a = 10;
1c = a * 2 + 3;
return c;
```
在第二行代码时输出 `Err`，也就是报错；但这一报错我认为是在**语法分析**的步骤中报错的。
按照课本的算法，在词法分析步骤中，`1c` 会被拆解为 `1` 和 `c` 两个 token 作为输出；还是说我对词法分析和语法分析的区别或界限理解有误？

**Comment by GeneraluseAI** [comment]
@ZewanHuang 这一报错应该在词法分析的过程中就完成，你能够注意到，这个`1`后面紧接着的就是`c`，中间并没有空白符号进行分割，这使得我们有充足的信息知道这里的输入是不符合词法单元`标识符`的文法定义的，从而能够报错。如果是 `1 c = a * 2 + 3 `这样的话，那确实是应该被拆为两个 Token 并且在语法分析中处理。
同样的，虽然我们这次的词法实验没有要求分析八进制或者十六进制数，但形如 0x123 , 01234 这样的数我们是有足够信息在词法分析阶段就分析出其是 十六/八进制的，而且事实上他们也是应该在词法分析阶段完成的。

**Comment by GeneraluseAI** [comment]
@GeneraluseAI 你所说的这类问题往往应该根据具体的情况分析，实际上并没有一个放之四海而皆准的标准。
不过没有解释清楚这些边界情况的确是我们的失职，我们会在之后对实验进行改进。

**Comment by ZewanHuang** [comment]
@GeneraluseAI 首先就八进制、十六进制数方面，我同意应该在词法分析阶段完成，因为可以将其定义为不同的类别，与标识符等为不同的类别，也自然需要分析出十六/八进制。

我的问题主要在于：**词法分析报错的范围或界限**。

> 当输入含三个或更多个 `=` 时，比如 `a === b`，正确输出应该是什么？
> 
> * [ ]  `Eq\nAssign`
> * [ ]  `Assign\nEq`
> * [ ]  `Err` 并结束

如果以中间有无空白符号来区分我们是否有充足信息确认正误，那按理上面这个问题应该是 `Err`，因为它不符合实验要求中任何类别的定义；如果是 `== =`，才能输出 `Eq\nAssign`。
但我在想，空白符号是否能用以分割Token，毕竟在课本的算法中，空白符号在扫描前就去除了。

**Comment by ZewanHuang** [comment]
> @GeneraluseAI 你所说的这类问题往往应该根据具体的情况分析，实际上并没有一个放之四海而皆准的标准。
> 不过没有解释清楚这些边界情况的确是我们的失职，我们会在之后对实验进行改进。（虽然我们这个实验现在还没发布）

确实感觉没有皆准的标准。
Support!

**Comment by Codevka** [comment]
实验指导中已经进行了相应的修改。
- `1c` 应拆解成两个 token `1` 和 `c`，**实验指导存在一定错误**，已改正；
-  `===` 应按最长匹配原则，输出 `Eq\nAssign`；
- 另，空格、制表符、换行符应当用于分割 token。gcc/clang 遇到形如 `a = 1 0;` 的代码会报错，说明词法分析时保留了空白符，到语法分析时发现存在错误。对于我们的词法分析程序，不需要将空白符作为一个 token，但需要其发挥分割的作用。
