### ISSUE TITLE
pre对代码语言有要求吗？

### ISSUE THREAD

**Issue by yunniw2001** [BUAA-SE-Compiling/miniSysY-tutorial#19]
如果对代码没有要求，那本次实验可不可以在windows环境下用python/java编写？

后续的实验中会涉及到pre实验的代码吗？如果涉及到，需不需要统一代码语言，在ubuntu环境下用C编写？

**Comment by GeneraluseAI** [comment]
@yunniw2001 1.对代码没有要求，你可以自由选择环境和语言，我们要求下载   LLVM 的工具链仅仅是为了方便同学们在本地检查自己生成的代码是否符合标准。

2.后续实验不会涉及到 pre 实验的代码。
