### ISSUE TITLE
关于LLVM IR语法的问题

### ISSUE THREAD

**Issue by 19231224lhr** [BUAA-SE-Compiling/miniSysY-tutorial#27]
助教学长，这是我的程序根据一段代码生成的LLVM IR代码，但是我用Linux执行lli时却报错了，我始终找不到为啥这样写是错的：
源程序
```c
int main () {
    int a;
    int b;
    int c;
    int d;
    a = 5;
    b = 5;
    c = 1;
    d = -2;
    d = (c * 1 / 2)  + (a - b);
    return e;
}
```
我生成的LLVM IR代码：
```c
define dso_local i32 @main(){
%1 = alloca i32
%2 = alloca i32
%3 = alloca i32
%4 = alloca i32
store i32 5, i32* %1
store i32 5, i32* %2
store i32 1, i32* %3
%x5 = sub i32 0,2
store i32 %5, i32* %4
%6 = load i32, i32* %3
%7 = load i32, i32* %1
%8 = load i32, i32* %2
%9 = mul i32 %6,1
%10 = sdiv i32 %9,2
%11 = sub i32 %7,%8
%12 = add i32 %10,%11
store i32 %12, i32* %4
ret i32 %12
}
}
```
报错原因：
```shell
hanser@hanser-virtual-machine:~/Desktop$ lli main.ll
lli: main.ll:11:1: error: instruction expected to be numbered '%5'
%6 = load i32, i32* %3
^
```
我觉得这样的LLVM IR形式代码应该没有问题吧，遇到-2，使用`%x5 = sub i32 0,2`生成，并存储到了d中，那下面不应该就是`%6 = load i32, i32* %3`加载c的值了吗，我不知道为什么会报这个错误。
![image](https://user-images.githubusercontent.com/70199004/139541117-77ec1bc4-066b-415a-bb34-a9f27bd1ab6e.png)
![image](https://user-images.githubusercontent.com/70199004/139541156-914bb903-39b3-4d5a-80f4-59c88a4f1b06.png)

**Comment by 19231224lhr** [comment]
啊，我好像知道为啥了，前面有一句我多输出了一个`x`，不知道是不是这个原因，明天早上起来再看看吧（
![image](https://user-images.githubusercontent.com/70199004/139541298-26ead08b-5ac9-47ec-8e9f-5a59cc197e3d.png)

**Comment by lynzrand** [comment]
@19231224lhr 请允许我引用群友的讨论回答这个问题：

> ✨Codevka💫, [10/21/21, 5:06 PM]
命名这种事只要不是按数字来就不会错
>
> ✨Codevka💫, [10/21/21, 5:08 PM]
LLVM 碰到数字就要严格递增

**Comment by Codevka** [comment]
命名相关问题在指导书的[这个地方](https://buaa-se-compiling.github.io/miniSysY-tutorial/pre/design_hints.html)有介绍。

**Comment by 19231224lhr** [comment]
> @19231224lhr 请允许我引用助教的讨论回答这个问题：
> 
> > ✨Codevka💫, [10/21/21, 5:06 PM]
> > 命名这种事只要不是按数字来就不会错
> > ✨Codevka💫, [10/21/21, 5:08 PM]
> > LLVM 碰到数字就要严格递增

谢谢，问题解决了~

**Comment by 19231224lhr** [comment]
> 命名相关问题在指导书的[这个地方](https://buaa-se-compiling.github.io/miniSysY-tutorial/pre/design_hints.html)有介绍。

收到！
